name: Update Playlist
on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate Separate Playlists
        run: |
          # القناة الأولى - Dream
          echo "#EXTM3U" > dream.m3u
          echo "#EXT-X-STREAM-INF:CLOSED-CAPTIONS=NONE,RESOLUTION=1920x1080,FRAME-RATE=50.000,CODECS=\"avc1.42c01f,mp4a.40.2\",AVERAGE-BANDWIDTH=3010000,BANDWIDTH=3770000" >> dream.m3u
          echo "http://line.dream-4k.cc:80/live/9142DC/107CC6/1440477.ts" >> dream.m3u

          # القناة الثانية - Tornado
          echo "#EXTM3U" > tornado.m3u
          echo "#EXT-X-STREAM-INF:CLOSED-CAPTIONS=NONE,RESOLUTION=1920x1080,FRAME-RATE=50.000,CODECS=\"avc1.42c01f,mp4a.40.2\",AVERAGE-BANDWIDTH=3010000,BANDWIDTH=3770000" >> tornado.m3u
          echo "http://tornado-pro.com:80/live/alhomaidirashid@gmail.com/HOrashid1/160239.ts" >> tornado.m3u

      - name: Push Changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add dream.m3u tornado.m3u
          git commit -m "Update playlists with full metadata" || exit 0
          git push
