name: Update Playlist
on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate Separate Files
        run: |
          # ملف القناة الأولى
          echo "http://line.dream-4k.cc:80/live/9142DC/107CC6/1440477.ts" > dream.ts
          # ملف القناة الثانية
          echo "http://tornado-pro.com:80/live/alhomaidirashid@gmail.com/HOrashid1/160239.ts" > tornado.ts

      - name: Push Changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add dream.ts tornado.ts
          git commit -m "Update separate channels" || exit 0
          git push
